# Add a warning to the issue description when the issue is labeled "Needs ..."
# and doesn't have a warning yet, and remove it again when all such labels are removed.
name: "Add or remove not-ready-for-PR warning"

permissions:
  contents: read
  #issues: write

on:
  issues:
    types: [opened, labeled, unlabeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GHITHUB_REPO: ${{ github.repository }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install PyGithub
        run: pip install -Uq PyGithub
      - name: Checkout repository
        uses: actions/checkout@v6

  add_not_ready_for_PR_warning:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.action == 'opened' || (github.event.action == 'labeled' && startsWith(github.event.label.name, 'Needs'))
    steps:
      - name: Add not-ready-for-PR warning
        run: |
          python .github/scripts/add_or_remove_no_pr_warning.py --mode="add"
      
  remove_not_ready_for_PR_warning:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.action == 'unlabeled' && startsWith(github.event.label.name, 'Needs')
    steps:
      - name: Remove not-ready-for-PR warning
        run: |
          python .github/scripts/add_or_remove_no_pr_warning.py --mode="remove"
